// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package search

type CreatePullPointFunction struct{}

func (_ *CreatePullPointFunction) Request() interface{} {
	return &CreatePullPoint{}
}
func (_ *CreatePullPointFunction) Response() interface{} {
	return &CreatePullPointResponse{}
}

type DestroyPullPointFunction struct{}

func (_ *DestroyPullPointFunction) Request() interface{} {
	return &DestroyPullPoint{}
}
func (_ *DestroyPullPointFunction) Response() interface{} {
	return &DestroyPullPointResponse{}
}

type EndSearchFunction struct{}

func (_ *EndSearchFunction) Request() interface{} {
	return &EndSearch{}
}
func (_ *EndSearchFunction) Response() interface{} {
	return &EndSearchResponse{}
}

type FindEventsFunction struct{}

func (_ *FindEventsFunction) Request() interface{} {
	return &FindEvents{}
}
func (_ *FindEventsFunction) Response() interface{} {
	return &FindEventsResponse{}
}

type FindMetadataFunction struct{}

func (_ *FindMetadataFunction) Request() interface{} {
	return &FindMetadata{}
}
func (_ *FindMetadataFunction) Response() interface{} {
	return &FindMetadataResponse{}
}

type FindPTZPositionFunction struct{}

func (_ *FindPTZPositionFunction) Request() interface{} {
	return &FindPTZPosition{}
}
func (_ *FindPTZPositionFunction) Response() interface{} {
	return &FindPTZPositionResponse{}
}

type FindRecordingsFunction struct{}

func (_ *FindRecordingsFunction) Request() interface{} {
	return &FindRecordings{}
}
func (_ *FindRecordingsFunction) Response() interface{} {
	return &FindRecordingsResponse{}
}

type GetCurrentMessageFunction struct{}

func (_ *GetCurrentMessageFunction) Request() interface{} {
	return &GetCurrentMessage{}
}
func (_ *GetCurrentMessageFunction) Response() interface{} {
	return &GetCurrentMessageResponse{}
}

type GetEventSearchResultsFunction struct{}

func (_ *GetEventSearchResultsFunction) Request() interface{} {
	return &GetEventSearchResults{}
}
func (_ *GetEventSearchResultsFunction) Response() interface{} {
	return &GetEventSearchResultsResponse{}
}

type GetMediaAttributesFunction struct{}

func (_ *GetMediaAttributesFunction) Request() interface{} {
	return &GetMediaAttributes{}
}
func (_ *GetMediaAttributesFunction) Response() interface{} {
	return &GetMediaAttributesResponse{}
}

type GetMessagesFunction struct{}

func (_ *GetMessagesFunction) Request() interface{} {
	return &GetMessages{}
}
func (_ *GetMessagesFunction) Response() interface{} {
	return &GetMessagesResponse{}
}

type GetMetadataSearchResultsFunction struct{}

func (_ *GetMetadataSearchResultsFunction) Request() interface{} {
	return &GetMetadataSearchResults{}
}
func (_ *GetMetadataSearchResultsFunction) Response() interface{} {
	return &GetMetadataSearchResultsResponse{}
}

type GetPTZPositionSearchResultsFunction struct{}

func (_ *GetPTZPositionSearchResultsFunction) Request() interface{} {
	return &GetPTZPositionSearchResults{}
}
func (_ *GetPTZPositionSearchResultsFunction) Response() interface{} {
	return &GetPTZPositionSearchResultsResponse{}
}

type GetRecordingInformationFunction struct{}

func (_ *GetRecordingInformationFunction) Request() interface{} {
	return &GetRecordingInformation{}
}
func (_ *GetRecordingInformationFunction) Response() interface{} {
	return &GetRecordingInformationResponse{}
}

type GetRecordingSearchResultsFunction struct{}

func (_ *GetRecordingSearchResultsFunction) Request() interface{} {
	return &GetRecordingSearchResults{}
}
func (_ *GetRecordingSearchResultsFunction) Response() interface{} {
	return &GetRecordingSearchResultsResponse{}
}

type GetRecordingSummaryFunction struct{}

func (_ *GetRecordingSummaryFunction) Request() interface{} {
	return &GetRecordingSummary{}
}
func (_ *GetRecordingSummaryFunction) Response() interface{} {
	return &GetRecordingSummaryResponse{}
}

type GetSearchStateFunction struct{}

func (_ *GetSearchStateFunction) Request() interface{} {
	return &GetSearchState{}
}
func (_ *GetSearchStateFunction) Response() interface{} {
	return &GetSearchStateResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() interface{} {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() interface{} {
	return &GetServiceCapabilitiesResponse{}
}

type PauseSubscriptionFunction struct{}

func (_ *PauseSubscriptionFunction) Request() interface{} {
	return &PauseSubscription{}
}
func (_ *PauseSubscriptionFunction) Response() interface{} {
	return &PauseSubscriptionResponse{}
}

type RenewFunction struct{}

func (_ *RenewFunction) Request() interface{} {
	return &Renew{}
}
func (_ *RenewFunction) Response() interface{} {
	return &RenewResponse{}
}

type ResumeSubscriptionFunction struct{}

func (_ *ResumeSubscriptionFunction) Request() interface{} {
	return &ResumeSubscription{}
}
func (_ *ResumeSubscriptionFunction) Response() interface{} {
	return &ResumeSubscriptionResponse{}
}

type SubscribeFunction struct{}

func (_ *SubscribeFunction) Request() interface{} {
	return &Subscribe{}
}
func (_ *SubscribeFunction) Response() interface{} {
	return &SubscribeResponse{}
}

type UnsubscribeFunction struct{}

func (_ *UnsubscribeFunction) Request() interface{} {
	return &Unsubscribe{}
}
func (_ *UnsubscribeFunction) Response() interface{} {
	return &UnsubscribeResponse{}
}
