// -*- Mode: Go; indent-tabs-mode: t -*-
//
// Copyright (C) 2022 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by gen_commands.py DO NOT EDIT.

package replay

type CreatePullPointFunction struct{}

func (_ *CreatePullPointFunction) Request() interface{} {
	return &CreatePullPoint{}
}
func (_ *CreatePullPointFunction) Response() interface{} {
	return &CreatePullPointResponse{}
}

type DestroyPullPointFunction struct{}

func (_ *DestroyPullPointFunction) Request() interface{} {
	return &DestroyPullPoint{}
}
func (_ *DestroyPullPointFunction) Response() interface{} {
	return &DestroyPullPointResponse{}
}

type GetCurrentMessageFunction struct{}

func (_ *GetCurrentMessageFunction) Request() interface{} {
	return &GetCurrentMessage{}
}
func (_ *GetCurrentMessageFunction) Response() interface{} {
	return &GetCurrentMessageResponse{}
}

type GetMessagesFunction struct{}

func (_ *GetMessagesFunction) Request() interface{} {
	return &GetMessages{}
}
func (_ *GetMessagesFunction) Response() interface{} {
	return &GetMessagesResponse{}
}

type GetReplayConfigurationFunction struct{}

func (_ *GetReplayConfigurationFunction) Request() interface{} {
	return &GetReplayConfiguration{}
}
func (_ *GetReplayConfigurationFunction) Response() interface{} {
	return &GetReplayConfigurationResponse{}
}

type GetReplayUriFunction struct{}

func (_ *GetReplayUriFunction) Request() interface{} {
	return &GetReplayUri{}
}
func (_ *GetReplayUriFunction) Response() interface{} {
	return &GetReplayUriResponse{}
}

type GetServiceCapabilitiesFunction struct{}

func (_ *GetServiceCapabilitiesFunction) Request() interface{} {
	return &GetServiceCapabilities{}
}
func (_ *GetServiceCapabilitiesFunction) Response() interface{} {
	return &GetServiceCapabilitiesResponse{}
}

type PauseSubscriptionFunction struct{}

func (_ *PauseSubscriptionFunction) Request() interface{} {
	return &PauseSubscription{}
}
func (_ *PauseSubscriptionFunction) Response() interface{} {
	return &PauseSubscriptionResponse{}
}

type RenewFunction struct{}

func (_ *RenewFunction) Request() interface{} {
	return &Renew{}
}
func (_ *RenewFunction) Response() interface{} {
	return &RenewResponse{}
}

type ResumeSubscriptionFunction struct{}

func (_ *ResumeSubscriptionFunction) Request() interface{} {
	return &ResumeSubscription{}
}
func (_ *ResumeSubscriptionFunction) Response() interface{} {
	return &ResumeSubscriptionResponse{}
}

type SetReplayConfigurationFunction struct{}

func (_ *SetReplayConfigurationFunction) Request() interface{} {
	return &SetReplayConfiguration{}
}
func (_ *SetReplayConfigurationFunction) Response() interface{} {
	return &SetReplayConfigurationResponse{}
}

type SubscribeFunction struct{}

func (_ *SubscribeFunction) Request() interface{} {
	return &Subscribe{}
}
func (_ *SubscribeFunction) Response() interface{} {
	return &SubscribeResponse{}
}

type UnsubscribeFunction struct{}

func (_ *UnsubscribeFunction) Request() interface{} {
	return &Unsubscribe{}
}
func (_ *UnsubscribeFunction) Response() interface{} {
	return &UnsubscribeResponse{}
}
